"""se cambia hasdhe password a solo password

Revision ID: 04842cfe36ae
Revises: dd80ea7eafb8
Create Date: 2025-04-23 20:31:51.830261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04842cfe36ae'
down_revision: Union[str, None] = 'dd80ea7eafb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('usuario', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'password')
    # ### end Alembic commands ###
