"""Add trip_id to stops and remove unique constraint on stop_id

Revision ID: 33f4ac9d2d73
Revises: 04842cfe36ae
Create Date: 2025-04-24 13:00:53.468311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f4ac9d2d73'
down_revision: Union[str, None] = '04842cfe36ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('trip_id', sa.String(), nullable=True))
    op.drop_index('ix_stops_stop_id', table_name='stops')
    op.create_index(op.f('ix_stops_stop_id'), 'stops', ['stop_id'], unique=False)
    op.create_index(op.f('ix_stops_trip_id'), 'stops', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stops_trip_id'), table_name='stops')
    op.drop_index(op.f('ix_stops_stop_id'), table_name='stops')
    op.create_index('ix_stops_stop_id', 'stops', ['stop_id'], unique=True)
    op.drop_column('stops', 'trip_id')
    # ### end Alembic commands ###
