"""Add stops and comments tables, update usuario

Revision ID: dd80ea7eafb8
Revises: a87fc8fa9866
Create Date: 2025-04-23 19:49:40.466223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd80ea7eafb8'
down_revision: Union[str, None] = 'a87fc8fa9866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_constraint('usuario_username_key', 'usuario', type_='unique')
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.drop_column('usuario', 'username')
    op.drop_column('usuario', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.create_unique_constraint('usuario_username_key', 'usuario', ['username'])
    op.drop_column('usuario', 'hashed_password')
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###
